syntax = "proto3";

package grpc.internal;

service AlertService {
  rpc GerarAlerta(GenerateAlertRequest) returns (GenerateAlertResponse);
  rpc DispararEmailAlerta(DispatchAlertEmailRequest) returns (DispatchAlertEmailResponse);
}

message GenerateAlertRequest {
  int64 panel_id = 1;
  string type = 2;
  string severity = 3;
}

message GenerateAlertResponse {
  int64 panel_id = 1;
  string type = 2;
  bool success = 3;
  int64 alert_id = 4;
  string created_at = 5;
}

message DispatchAlertEmailRequest {
  string to = 1;
  string template = 2;
  string subject = 3;
  int64 panel_id = 4;
  string severity = 5;
  float soiling_index = 6;
}

message DispatchAlertEmailResponse {
  string to = 1;
  bool success = 2;
  int64 alert_id = 3;
  string created_at = 4;
}
