ALTER TABLE grupos_solares
    ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;

ALTER TABLE placas
    ADD COLUMN IF NOT EXISTS potencia_wp NUMERIC(10, 2),
    ADD COLUMN IF NOT EXISTS inclinacao DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS azimute DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS coef_temperatura DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS data_instalacao DATE;
