-- SolarVision no Supabase: substitui as migrations Flyway e a API Spring Boot.
-- Auth = Supabase Auth; CRUD = PostgREST protegido por RLS; dashboard = funções SQL (RPC).

-- Perfil do usuário (a senha fica no Supabase Auth, em auth.users).
create table public.usuarios (
    id uuid primary key references auth.users (id) on delete cascade,
    nome varchar(100) not null,
    email varchar(255) not null unique,
    role varchar(30) not null default 'USER',
    criado_em timestamptz not null default now(),
    constraint ck_usuarios_role check (role in ('ADMIN', 'USER'))
);

create table public.grupos_solares (
    id bigint generated by default as identity primary key,
    nome varchar(120) not null,
    status varchar(30) not null default 'ATIVO',
    criado_em timestamptz not null default now(),
    constraint ck_grupos_solares_nome check (btrim(nome) <> ''),
    constraint ck_grupos_solares_status check (status in ('ATIVO', 'INATIVO', 'MANUTENCAO'))
);

create table public.placas (
    id bigint generated by default as identity primary key,
    grupo_id bigint not null references public.grupos_solares (id) on delete cascade,
    modelo varchar(120) not null,
    status varchar(30) not null default 'ATIVA',
    criado_em timestamptz not null default now(),
    constraint ck_placas_modelo check (btrim(modelo) <> ''),
    constraint ck_placas_status check (status in ('ATIVA', 'INATIVA', 'MANUTENCAO'))
);

create table public.limpezas (
    id bigint generated by default as identity primary key,
    placa_id bigint not null references public.placas (id) on delete cascade,
    data_limpeza timestamptz not null,
    observacao text,
    criado_em timestamptz not null default now(),
    constraint ck_limpezas_observacao check (char_length(observacao) <= 1000)
);

create table public.leituras_energia (
    id bigint generated by default as identity primary key,
    placa_id bigint not null references public.placas (id) on delete cascade,
    data_hora timestamptz not null,
    wats_gerados numeric(14, 4) not null,
    criado_em timestamptz not null default now()
);

create index idx_placas_grupo_id on public.placas (grupo_id);
create index idx_limpezas_placa_id on public.limpezas (placa_id);
create index idx_limpezas_data_limpeza on public.limpezas (data_limpeza desc);
create index idx_leituras_energia_placa_id on public.leituras_energia (placa_id);
create index idx_leituras_energia_data_hora on public.leituras_energia (data_hora);

-- RLS: o equivalente ao "anyRequest().authenticated()" do Spring Security.
alter table public.usuarios enable row level security;
alter table public.grupos_solares enable row level security;
alter table public.placas enable row level security;
alter table public.limpezas enable row level security;
alter table public.leituras_energia enable row level security;

create policy "usuario le o proprio perfil" on public.usuarios
    for select to authenticated using (id = (select auth.uid()));
create policy "autenticados gerenciam grupos" on public.grupos_solares
    for all to authenticated using (true) with check (true);
create policy "autenticados gerenciam placas" on public.placas
    for all to authenticated using (true) with check (true);
create policy "autenticados gerenciam limpezas" on public.limpezas
    for all to authenticated using (true) with check (true);
create policy "autenticados leem leituras" on public.leituras_energia
    for select to authenticated using (true);

grant select on public.usuarios, public.leituras_energia to authenticated;
grant select, insert, update, delete on public.grupos_solares, public.placas, public.limpezas to authenticated;

-- Cria o perfil quando alguém se cadastra (signUp envia o nome em options.data.nome).
create function public.criar_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.usuarios (id, nome, email)
    values (
        new.id,
        left(coalesce(nullif(btrim(new.raw_user_meta_data ->> 'nome'), ''), split_part(new.email, '@', 1)), 100),
        new.email
    );
    return new;
end;
$$;

create trigger ao_criar_usuario
    after insert on auth.users
    for each row execute function public.criar_perfil_usuario();

-- Gráfico de geração: potência média (W) por balde de tempo no fuso de São Paulo.
create function public.dashboard_metricas(
    granularidade text default 'dia',
    data_inicio timestamptz default null,
    data_fim timestamptz default null
)
returns table (x timestamptz, y numeric)
language plpgsql
stable
set search_path = ''
as $$
declare
    unidade text := case lower(coalesce(nullif(btrim(granularidade), ''), 'dia'))
        when 'hora' then 'hour'
        when 'dia' then 'day'
        when 'semana' then 'week'
        when 'mes' then 'month'
    end;
    inicio timestamptz := coalesce(data_inicio, now() - interval '7 days');
    fim timestamptz := coalesce(data_fim, now());
begin
    if unidade is null then
        raise exception 'Granularidade inválida. Use hora, dia, semana ou mes.' using errcode = '22023';
    end if;
    if inicio > fim then
        raise exception 'dataInicio deve ser anterior ou igual a dataFim.' using errcode = '22023';
    end if;

    return query
        select date_trunc(unidade, l.data_hora at time zone 'America/Sao_Paulo') at time zone 'America/Sao_Paulo',
               coalesce(avg(l.wats_gerados), 0)
        from public.leituras_energia l
        where l.data_hora between inicio and fim
        group by 1
        order by 1;
end;
$$;

-- Cards da Home: total gerado hoje, placas ativas e última limpeza.
create function public.dashboard_resumo()
returns json
language sql
stable
set search_path = ''
as $$
    select json_build_object(
        'totalGeradoHoje', (
            select coalesce(sum(wats_gerados), 0)
            from public.leituras_energia
            where data_hora between (date_trunc('day', now() at time zone 'America/Sao_Paulo') at time zone 'America/Sao_Paulo')
                                and now()
        ),
        'placasAtivas', (select count(*) from public.placas where status = 'ATIVA'),
        'ultimaLimpeza', (
            select json_build_object(
                'id', l.id,
                'placaId', l.placa_id,
                'placaModelo', p.modelo,
                'dataLimpeza', l.data_limpeza,
                'observacao', l.observacao
            )
            from public.limpezas l
            join public.placas p on p.id = l.placa_id
            order by l.data_limpeza desc, l.id desc
            limit 1
        )
    );
$$;

revoke execute on function public.dashboard_metricas(text, timestamptz, timestamptz) from public, anon;
revoke execute on function public.dashboard_resumo() from public, anon;

-- "Tempo real": o seeder desloca o CSV para terminar hoje; este job repete o deslocamento
-- todo dia às 00:05 de São Paulo (03:05 UTC), como fazia cada `docker compose up`.
create extension if not exists pg_cron;

select cron.schedule(
    'deslocar-leituras-para-hoje',
    '5 3 * * *',
    $$
    update public.leituras_energia
    set data_hora = data_hora + make_interval(days => d.dias)
    from (
        select (now() at time zone 'America/Sao_Paulo')::date
             - (max(data_hora) at time zone 'America/Sao_Paulo')::date as dias
        from public.leituras_energia
    ) d
    where d.dias > 0
    $$
);
