-- Alertas: avisam o dono, sem ele abrir o Monitoramento, do que as análises já detectam
-- (limpeza recomendada, previsão de amanhã bem abaixo da média de 5 anos e placa rendendo abaixo do grupo).
-- Gerados pelo pg_cron às 07:00 de São Paulo; o dono só lê e marca como lido.
-- ponytail: só no sino do app; e-mail/push quando houver provedor configurado.

-- referencia evita repetição: previsão baixa = o dia previsto (um por dia); limpeza e desempenho = a segunda-feira
-- da semana (enquanto a situação durar, no máximo um lembrete por semana, lido ou não).
create table public.alertas (
    id bigint generated by default as identity primary key,
    grupo_id bigint not null references public.grupos_solares (id) on delete cascade,
    placa_id bigint references public.placas (id) on delete cascade, -- null: alerta do grupo
    tipo varchar(30) not null,
    mensagem text not null,
    referencia date not null,
    criado_em timestamptz not null default now(),
    lido_em timestamptz,
    constraint ck_alertas_tipo check (tipo in ('LIMPEZA', 'PREVISAO_BAIXA', 'DESEMPENHO')),
    constraint uq_alertas_referencia unique nulls not distinct (grupo_id, placa_id, tipo, referencia)
);

alter table public.alertas enable row level security;
create policy "alertas dos grupos visiveis" on public.alertas
    for all to authenticated
    using (grupo_id in (select g.id from public.grupos_solares g))
    with check (grupo_id in (select g.id from public.grupos_solares g));
-- O dono lê e marca como lido; o resto só o gerar_alertas escreve.
revoke all on public.alertas from anon, authenticated;
grant select, update (lido_em) on public.alertas to authenticated;

-- Roda para todos os grupos (security definer: vê todas as placas; sem JWT, perda_sujeira_em também).
-- Previsão baixa: amanhã < 60 % da média de dashboard_historico para o dia (a mesma do gráfico). No último ano,
-- 14 % dos dias de Florianópolis e 4 % dos de Natal ficaram abaixo disso (~1 alerta por semana no pior caso).
create function public.gerar_alertas()
returns void
language sql
security definer
set search_path = ''
as $$
    with hoje as (
        select (now() at time zone 'America/Sao_Paulo')::date as dia
    ), ref as (
        select hoje.dia + 1 as amanha,
               (hoje.dia + 1)::timestamp at time zone 'America/Sao_Paulo' as inicio,
               (hoje.dia + 2)::timestamp at time zone 'America/Sao_Paulo' as fim,
               date_trunc('week', hoje.dia)::date as semana
          from hoje
    )
    insert into public.alertas (grupo_id, placa_id, tipo, mensagem, referencia)
    select p.grupo_id, p.id, 'LIMPEZA', r.motivo, ref.semana
      from public.recomendacoes_limpeza() r
      join public.placas p on p.id = r.placa_id
     cross join ref
     where r.limpar and p.status = 'ATIVA'
    union all
    select p.grupo_id, p.id, 'DESEMPENHO',
           format('%s rendeu %s%% do estimado nos últimos 7 dias; o grupo, %s%%',
                  p.modelo, round(r.desempenho * 100), round(r.desempenho_grupo * 100)),
           ref.semana
      from public.ranking_placas(now() - interval '7 days', now()) r
      join public.placas p on p.id = r.placa_id
     cross join ref
     where r.anomalia and p.status = 'ATIVA'
    union all
    select g.id, null, 'PREVISAO_BAIXA',
           format('Amanhã (%s) a previsão é de %s kWh: %s%% da média de %s %s para o dia (%s kWh)',
                  to_char(ref.amanha, 'DD/MM'), replace(round((prev.wh / 1000)::numeric, 1)::text, '.', ','),
                  round((prev.wh / h.media_wh * 100)::numeric), h.anos, case h.anos when 1 then 'ano' else 'anos' end,
                  replace(round(h.media_wh / 1000, 1)::text, '.', ',')),
           ref.amanha
      from public.grupos_solares g
     cross join ref
     cross join lateral (
           select sum(gh.estimada_wh) as wh
             from public.geracao_horaria gh
            where gh.grupo_id = g.id and gh.data_hora >= ref.inicio and gh.data_hora < ref.fim
     ) prev
     cross join lateral public.dashboard_historico('dia', ref.inicio, ref.fim - interval '1 millisecond', g.id) h
     where g.status = 'ATIVO' and prev.wh < 0.6 * h.media_wh
    on conflict do nothing;
$$;

revoke execute on function public.gerar_alertas() from public, anon, authenticated;

-- 07:00 de São Paulo (10:00 UTC).
select cron.schedule('gerar-alertas', '0 10 * * *', 'select public.gerar_alertas()');
